### PR TITLE
Refactoring transfer of apps between orgs

### LINKED ISSUE #238: When Alameda partner transfers an application, applicant should be notified
Right now an applicant doesn't know if APD transfers a case to EBCLC or vice versa. They should be notified when this happens to prevent confusion.

### LINKED ISSUE #309: Check that transfer logic is okay
Situation: Org A sends a status notification. Org A then transfers the application to Org B (example: status update is "can't proceed" because income information is missing, once applicant provides that information, Org A realizes they need to be handled by Org B and does the transfer). 

Question: what happens to the status updates and how should they look to Org B after transfer?

### LINKED ISSUE #374: Show transfers and other important events in the application history
The application history view currently only shows status updates. It would be useful if it also showed when an application was transferred between orgs.

### LINKED ISSUE #451: Rebuild app transfer between orgs. Mega task.  Waiting on #571, needs discussion.
- [x] create ApplicationTransfer model based on StatusUpdate, along with "Transferred" StatusType #474

### The org user who is sending the transfer:

- [x] clicks on the transfer applicant button
- [x] they get a form which lets them:
	- [x] select which org to transfer to
	- [x] enter a reason (which will be sent to the receiving org)
	- [x] review and edit the notification that will be sent to the applicant
- on submission of the form:
	- [x] send a notification to the applicant #238
	- [x] tie a new event to the application that includes the "why" message
- [x] gets a flash message that the app has been transferred
- [x] Should see the app with a status type of "transferred" and should not be able to access it's details or history. #471 

### The receiving org user should:

- [x] see the new app in a bundle
- [x] it should be marked as a transfer
- [x] they should be able to see the transfer in the application history #374
- [x] they should be able to see previous status updates from the sending org in the app history #309

### LINKED ISSUE #471: Add outgoing transferred apps to app index
L and V requested that when an app is transferred, that we do not delete it from their App Index. Instead, keep it there with a note that it was transferred to the other org.

### PR DESCRIPTION
**Pull request by bengolder**
# Transfers between Organizations

- closes #451
- closes #238
- closes #374
- closes #471
- closes #309

## Refactoring transfer relationships

1b3276d2271518ef0e5bc5d5083fa029b101fb14

Before this refactor, the `Organization` model had a method, `get_transfer_org` which hardcoded the transfer capability between organizations.
```python
# in user_accounts/models/organization.py
def get_transfer_org(self):
    """If this organization is allowed to transfer to another
    organization, this shoud return the other organization they are
    allowed to transfer submissions to.
    """
    if self.slug == constants.Organizations.ALAMEDA_PUBDEF:
        return self.__class__.objects.get(
            slug=constants.Organizations.EBCLC)
    elif self.slug == constants.Organizations.EBCLC:
        return self.__class__.objects.get(
            slug=constants.Organizations.ALAMEDA_PUBDEF)
    return None
```

As we add more organizations, we may wish to set up more relationships. First I want to simplify this code by adding a transfer relationship between organizations.

```python
class Organization(models.Model):
    ...
    can_transfer_applications = models.BooleanField(default=False)
    transfer_partners = models.ManyToManyField(
        'self', symmetrical=True, blank=True)
```

The `can_transfer_applications` flag allows us to check whether to perform additional queries that would be necessary for orgs that transfer applications.

Now, in our `organizations.json` fixture, we can modify EBCLC and Alameda Pub Def to set this transfer relationship.

```json
{
  "model": "user_accounts.organization",
  "fields": {
    "name": "East Bay Community Law Center",
    "can_transfer_applications": true
  }
},
{
  "model": "user_accounts.organization",
  "fields": {
    "name": "Alameda County Public Defender's Office",
    "can_transfer_applications": true,
    "transfer_partners": [
        ["East Bay Community Law Center"]
    ]
  }
},
```

Finally, we can now query transfer capability and specific partners in a cleaner, more flexible way:

```python
# boolean flag
if org.can_transfer_applications:
    # additional query
    transfer_options = org.transfer_partners.all()
```

## Adding a new status type

e36177b8eb6bd54a265a0c2b591a94be41aaed1d

This new `Transferred` status type should not appear in the status types listed when an org user is sending a new status update. Currently, the `is_active` boolean flag on status types will control whether or not they show up in the list of possible status types. But semantically, it means something different, it indicates a status type that is no longer used. Therefore, we will add a new flag that specifically excludes status types from the options, called `is_a_status_update_choice`. The cost of adding a boolean flag is minimal, so adding such a specific flag is not a concern.

```python
# template_option.py
class TemplateOption(models.Model):
    ...
    is_a_status_update_choice = models.BooleanField(default=True)
```

Now we can add a fixture for the `Transferred` status type:

```json
{
  "model": "intake.statustype",
  "pk": 8,
  "fields": {
    "label": "Transferred",
    "display_name": "Transferred",
    "template": "Your {{county}} application is now being handled by {{to_organization_name}}. {{to_organization_next_step}}",
    "help_text": "",
    "slug": "transferred",
    "is_a_status_update_choice": false
  }
},
```

We can also enumerate our hardcoded status types in our code as a series of constants.

```python
# in intake/models/status_type.py
# all of these are defined in the `template_options.json` fixture
CANT_PROCEED = 1
NO_CONVICTIONS = 2
NOT_ELIGIBLE = 3
ELIGIBLE = 4
COURT_DATE = 5
OUTCOME_GRANTED = 6
OUTCOME_DENIED = 7
TRANSFERRED = 8
```

## Adding the ApplicationTransfer model

- 9fe0083 `remove incorrect application transfer migration`
- 3bec3dc `add ApplicationTransfer model`

Currently, during a transfer, we actually delete the old application. What if, instead, we created a new application and flagged the old one, adding a new transfer model that links between the transfer status update and the newly created application?

### Flagging the old app as transferred

612dcff `add created, updated, was_transferred fields to Application`

Using `was_transferred_out`, we can clearly mark old apps as having been transferred. The `_out` portion should clarify which org was responsible for the transfer (the one tied to this application).

```python
class Application(models.Model):
    ...
    was_transferred_out = models.BooleanField(default=False)
```

It's likely that in the long run, we will want to give additional flags or properties to the relationship between an applicant and the org handling their application. For example, if we allow orgs to collaborate, or if we explicitly mark orgs as having abandoned an application, or if an applicant does not wish to work with an org further. In this picture, it would make sense to have flags on an `Application` object.

Our application transfers can be a simple link between the status update that created them (which has the `transferred` status type), and the new application to the target organization.

```python
class ApplicationTransfer(models.Model):
    """A record that links a 'Transferred' status update to the new application
    created from the transfer.
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status_update = models.OneToOneField(
        'intake.StatusUpdate', related_name='transfer',
        on_delete=models.CASCADE)
    new_application = models.ForeignKey(
        'intake.Application', related_name='incoming_transfers',
        on_delete=models.PROTECT)
    reason = models.TextField(blank=True)

    def __str__(self):
        return '{} because "{}"'.format(
            self.status_update.__str__(),
            self.reason)
```

When we perform the transfer, it's important that we no longer delete the old application, but instead set the boolean flag. The full transfer process is 4 queries total, saving 3 new objects (status update, application, application_transfer) and updating the existing application object.

- 347397f `create and test applications services`

```python
def transfer_application(author, application, to_organization, reason):
    """Transfers an application from one organization to another
    """
    transfer_status_update = models.StatusUpdate(
        status_type=models.status_type.TRANSFERRED,
        author=author,
        application=application
    )
    transfer_status_update.save()
    new_application = models.Application(
        form_submission=application.form_submission,
        organization=to_organization)
    new_application.save()
    transfer = models.ApplicationTransfer(
        status_update=transfer_status_update,
        new_application=new_application,
        reason=reason)
    transfer.save()
    application.was_transferred_out = True
    application.save()
```

Adding these additional queries to the transfer step means that the cost is placed on a step that occurs rarely, rather than at the time of display or retrieval, which occurs more often.

## The Application Index

The dilemmas of querying for the application index drove much of the solutions above.

Pagination is an important factor here, because it means that we want to return one ordered query, that is _then_ paginated, as opposed to two queries and then sorting them into one combined list.

We need a way to order applications in the database query that _does not_ rely on `date_received`, and is a better representation of when the application was sent to the organization. We can accomplish this with a `created` attribute on `Application`.

```python
class Application(models.Model):
    ...
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
```

### Getting queries for the receiving organization

For displaying the latest status, we have a serializer post-processing step that preselects the latest status from all the status updates for an application:

```python
class ApplicationFollowupListSerializer(serializers.ModelSerializer):
    organization = serializers.SlugRelatedField(
        read_only=True, slug_field='slug')
    status_updates = MinimalStatusUpdateSerializer(many=True)

    class Meta:
        model = models.Application
        fields = [
            'organization',
            'status_updates'
        ]

    def to_representation(self, *args, **kwargs):
        data = super().to_representation(*args, **kwargs)
        sorted_status_updates = sorted(
            data.get('status_updates', []), key=lambda d: d['updated'],
            reverse=True)
        latest_status = \
            sorted_status_updates[0] if sorted_status_updates else None
        data.update(latest_status=latest_status)
        return data
```

We would want some similar step for the receiving organization that would flag incoming applications as having been recently transferred.

```python
class ApplicationIndexWithTansfersSerializer(ApplicationFollowupListSerializer):
    organization = serializers.SlugRelatedField(
        read_only=True, slug_field='slug')
    status_updates = MinimalStatusUpdateSerializer(many=True)
    incoming_transfers = TransferSerializer(many=True)

    class Meta:
        model = models.Application
        fields = [
            'organization',
            'status_updates',
            'incoming_transfers'
        ]
```

Assuming a `TransferSerializer` that includes `organization_name` and `local_date`, we can now clearly flag incoming transfers:

```html+jinja
  <td>
    {# Status #}
    {% if application.latest_status %}
        
    {%- elif application.incoming_transfers -%}
        Transferred from {{
            application.incoming_transfers[0].organization_name
        }}  {{ 
            humanize.naturaltime(application.incoming_transfers[0].local_date)
        }}
    {%- else %}
      New
    }
    {% endif %}
  </td>
```

### Queries for the sending organization

Because we added the `was_transferred_out_flag` to `Application`, it's easy to display transferred apps differently.

```html+jinja
{%- for application in applications %}
    {%- if application.was_transferred_out %}
        {%- include "application-transfer-display.jinja" %}
    {%- else %}
        {%- include "application-display.jinja" %}
    {%- endif %}
{%- endfor %}
```

### App index queries and serializers

When querying for the app index, we need extra queries, but only for orgs that do transfers. We also need to paginate and serialize based on whether or not the org does transfers. The seralizers should make use of inheritance and pull in all the fields necessary for display in the app index.

First, we should paginate the queryset. Second, we should serialize the objects returned by the paginated queryset. This can be accomplish by updating the `object_list` attribute of a `Page` instance, changing it from a queryset into a serialized queryset.

- ef4acf0 `add serializer for pagination`
- 547edbe `move pagination to a service`

```python
# in intake/services/pagination.py
def get_serialized_page(qset, serializer, page_index, **kwargs):
    page = get_page(qset, page_index, **kwargs)
    page.object_list = serializer(page.object_list, many=True).data
    return page
```

The edited `Page` instance will function exactly the same as a non-serialized `Page`, and it can be iterated over like a normal queryset or serialized queryset.

Once we add some serializers that are specific to the app index, we can handle the query in one function while combining pagination and serialization in another.

- a60f309 `add new app index serializers`
- 347397f `create and test applications services`

```python
# in intake/services/applications_service.py
def get_applications_for_org(organization):
    prefetch_tables = [
        'form_submission',
        'status_updates',
        'status_updates__status_type',
    ]
    if organization.can_transfer_applications:
        prefetch_tables += [
            'incoming_transfers',
            'incoming_transfers__status_update',
            'incoming_transfers__status_update__organization',
        ]
    return models.Application.objects.filter(
            organizations=organization
        ).prefetch_related(*prefetch_tables).order_by('-created').distinct()


def get_applications_index_for_org_user(user, page_index):
    """Paginates and serializes applications for an org user
    """
    organization = user.profile.organization
    page = paginated(
        get_applications_for_org(organization), page_index)
    serializer = serializers.ApplicationIndexSerializer
    if organization.can_transfer_applications:
        serializer = \
            serializers.ApplicationIndexWithTansfersSerializerSerializer
    return serializers.serialize_page(page, serializer)
```

## Application history

In our application history, we can use the organization's transfer flag to decide whether or not to pull another org's status updates prior to the transfer.

```python
from django.db.models import Q

def get_status_updates_for_application(application):
    are_updates_for_this_app = Q(
        application=application)
    queryset = models.StatusUpdate.objects.filter(are_updates_for_this_app)
    if application.organization.can_transfer_applications:
        transfer = application.incoming_transfers.latest('created')
        if transfer:
            are_updates_prior_to_a_transfer = Q(
                application_id=transfer.status_update.application_id,
                updated__lte=transfer.status_update.updated)
            queryset = models.StatusUpdate.objects.filter(
                are_updates_for_this_app | are_updates_prior_to_a_transfer )
    return queryset.order_by('-updated')
```

Next Steps:
- [x] make an abstract base model with `created` & `updated` fields
- [x] update the `Application` model with all new flags, such as `was_transferred_out`
- [x] create the new `ApplicationTransfer` model
- [x] create PaginationSerializer
- [x] create new Application serializers
- [x] build and test the paginated queries for app index services
- [x] build and test the app history query
- [x] update the app index template
- [x] update the app history template
- [x] create the necessary services to support application transfer views.
- [x] create the application transfer form
- [x] create the application transfer form views
- [x] make sure the full application transfer workflow is has the necessary tests.

### CODE REVIEW

**Comment by bengolder** [comment]
Currently looking at how to manage pagination along with serialization.
It looks like they have a clearly documented solution, involving a special serializer class:
http://djangorestframework.readthedocs.io/en/latest/api-guide/pagination/

**Comment by bengolder** [comment]
Next Steps:
- [ ] make an abstract base model with `created` & `updated` fields
- [ ] update the `Application` model with all new flags `was_transferred_out`
- [ ] create the new `ApplicationTransfer` model
- [ ] create new serializers
- [ ] build and test the paginated queries app index services
- [ ] build and test the app history query
- [ ] update the app index template
- [ ] update the app history template
- [ ] create the necessary services to support application transfer views.
- [ ] create the application transfer form
- [ ] create the application transfer form views
- [ ] make sure the full application transfer workflow is has the necessary tests.

**Comment by bengolder** [comment]
It looks like `PaginationSerializer` was [removed from Django REST Framework](http://www.django-rest-framework.org/topics/3.1-announcement/#pagination), so I'm going to have to build our own. The pagination functionality that remains in Django REST Framework is used at the level of the view, for API views, and handles query parameters. Since we are not implementing it at that level, we'll have to roll our own integration of pagination and serialization.

**Comment by bengolder** [comment]
Good news. The [implementation of `PaginationSerializer` looks simple](https://github.com/tomchristie/django-rest-framework/blob/b106ebd2c0a19107f12d5b87cfbe0083aaaa60b9/rest_framework/pagination.py#L77), so it shouldn't be too hard to roll our own. Apparently it used [some poorly documented functionality for serializer fields, `source='*'`](https://github.com/tomchristie/django-rest-framework/issues/2032).

**Comment by bengolder** [comment]
It was really easy to replace the core functionality of the `PaginationSerializer`. This tiny function does what we need:

```python
def serialize_page(page, serializer, many=True):
    page.object_list = serializer(page.object_list, many=many).data
    return page
```

```python
queryset = models.FormSubmission.objects.all()
page = Paginator(queryset, 2).page(2)
serialized_page = serializers.serialize_page(
	page, serializers.FormSubmissionSerializer)
for submission in serialized_page:
	# do something
```

**Comment by bengolder** [comment]
A preview of how these work out in the interface.

On the application index page, this is as much detail as seemed reasonable to me without significantly altering the design of app listings in order to accommodate more information. If I were to add the names of the to or from orgs, then I would have break out the long organization names into multiline spaces, reducing the space for other columns in the process.

I felt that it made sense to allow them to continue to access the detail and printout for outgoing transfers.

screen shot 2017-03-16 at 4 44 04 pm


On the app history page, I replaced additional info and next steps with the reason, the target organization, and an example of the default message.

screen shot 2017-03-16 at 4 33 28 pm

**Comment by bengolder** [comment]
@glassresistor This PR seems to be unable to generate review apps, despite having merged develop.
When on the `had a problem` link, I get an error saying that I don't have permission to see the page.

screen shot 2017-03-16 at 11 37 20 pm

Since this PR introduces a number of UI and workflow changes, it would be great to be able to review it as a live app if possible.

**Comment by bengolder** [comment]
This needs some minor fixes and checks before merging.

- [x] It requires #572 in order to be able to properly load the new transfer data into the review app.
- [x] It needs a few more tests of permissions and content
- [ ] We should review how this affects transfers, permissions, and the different UI outputs.

**Review by jennifermarie — APPROVED** [review]

**Pull request merged**
