### PR TITLE
Feature/remove mock fixtures from deploy

### PR DESCRIPTION
**Pull request by glassresistor**
This PR removes all fake data fixtures from the repo.

_This PR does not include any migrations_

Changes:
- deletes all fake submission fixture files, as well as event fixture files associated with them.
- deletes all fake user profile fixture files.
- `./manage.py new_fixtures` **will destroy any existing data** and create new fake data from scratch, and save that fake data to local fixture files.
- `./manage.py new_fixtures` **needs to be run once before `make test` will pass**
- travis will automatically run `./manage.py new_fixtures`
- If we want the fake data to change, or add a new organization, we must manually run `./manage.py new_fixtures` on `cmr-prod`, `cmr-demo`, or `cmr-develop`.
- adds some factories and useful functions to `user_accounts.tests.factories`

### CODE REVIEW

**Comment by glassresistor** [comment]
I've also updated some of travis so it runs faster by caching the pip and node_modules files between test runs.

**Comment by bengolder** [comment]
UAT:
- [x] can login to PR app with secret envvar-based password
- [ ] can login to PR app with secret envvar-based password on cmr-demo

Final steps:
- [x] set `TEST_USER_PASSWORD` environmental variable on `cmr-develop` and `cmr-demo`

*New deploy step*
- after merging into `cmr-develop` or `cmr-demo`, manually run: `heroku run ./manage.py new_fixtures --app cmr-develop`

**Comment by glassresistor** [comment]
It should already be set on cmr-develop but demo will need it

**Comment by glassresistor** [comment]
I've been able to confirm that new_fixtures is  still not rebuilding users if they already exist.

Do reproduce it working flush the db and rebuild fixtures. 

```bash
./manage.py flush
./manage.py load_essential_data
# change the password
./manage.py new_fixtures
make tests # passes
# change the password again
./manage.py new_fixtures
make tests # fails
```

**Review by bengolder — APPROVED** [review]

**Review by jennifermarie — APPROVED** [review]
Approving because I was able to get things working locally, but would love an in-person walkthrough on this one to get up to speed on anything non-obvious :)

**Pull request merged**
