### PR TITLE
add a starter PR template

### LINKED ISSUE #1014: Add Template for Pull Requests
### Why

For development work, it would be helpful to add some minimal structure to reduce human error and increase reliability, consistency, and understanding.

### Origin

This came out of discussions with @jennifermarie @glassresistor & I about bugs that were missed during PR review and ways we could improve communication.

### Implementation

It's relatively simple. We can add `.github/PULL_REQUEST_TEMPLATE.md` to our repository with an initial structure, and then make further modifications to better fit our needs.

Github docs about this: https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

### PR DESCRIPTION
**Pull request by bengolder**
Closes #1014 

### What does this do and why?

This creates a basic template for Pull Requests to help improve documentation and consistency in our development process. When people open new pull requests on github, the message body will be autofilled with this template.

### Testing & Checks

This PR includes the following items (if checked):
- [ ] new dependencies
- [ ] migrations
- [ ] data migrations
- [ ] celery tasks
- [ ] changes to environment variables or local settings
- [x] configuration changes for 3rd party services (Travis, Heroku, AWS, Github, etc)
- [ ] visual or style changes

We need to make sure that the team feels like this template is a helpful beginning for clarifying development work. We can optimize it further down the road.
No automated tests are needed. No manual deployment changes are needed.

### Details

- adds the template at `.github/PULL_REQUEST_TEMPLATE.md`
- This PR itself (#1015) uses the proposed structure
- The template includes 5 sections:
    - any issues a PR closes
    - whether migrations or new dependencies are included
    - the problem solved by the PR
    - any testing or checks needed for the changes (automated or UAT)
    - implementation details to explain the PR

### CODE REVIEW

**Review by glassresistor — CHANGES_REQUESTED** [review]
I think this generally looks good.  The original issue was to make sure things we think are tasks actually run as tasks so I think we should add a line "This PR does (not) introduce a celery task"

**Comment by glassresistor** [comment]
Also we can add "This PR does (not) change affect infrastructure"

**Review by jennifermarie — APPROVED** [review]

**Review by glassresistor — APPROVED** [review]

**Comment by bengolder** [comment]
Incorporated feedback from @jazmynlatimer

**Comment by bengolder** [comment]
Accidentally closed instead of just commenting 😅

**Comment by bengolder** [comment]
Incorporated changes from @joduinn , shifting language from command-form to question form.

**Pull request merged**
