### PR TITLE
Feature/build assets with compress

### LINKED ISSUE #745: Add Compressor and integrate with testing and deploy
- [x] Add Ruby and Node to heroku
- [x]  Add requirements
- [x]  Add Compressor and configure 
- [x] Reorganize CSS and JS if necessary
- [x] Hijack collectstatic and add compressor

Optional run collectstatic on Travis

### PR DESCRIPTION
**Pull request by glassresistor**
closes #745

### CODE REVIEW

**Comment by glassresistor** [comment]
Once travis passes do a once over on the PR app to make sure static files work on heroku

**Comment by glassresistor** [comment]
This should be ready to merge in.  Its work locally and on Heroku.
On your local development machines run this after you pull for updates
```bash
rm -r project/static
./manage.py collectstatic -c --no-input
```

**Comment by bengolder** [comment]
The js files aren't being displayed in the templates.

You can manually tests this by checking for charts at:

https://cmr-develop-pr-763.herokuapp.com/stats/


This code in `templates/stats.jinja` is not producing an output in the html:

```jinja
{% compress 'js' %}
    <script type="text/browserify" src="{{ static('intake/js/stats_entry.js') }}"></script>
{% endcompress %}
```

**Comment by bengolder** [comment]
Before merging this, I think we should include some basic tests to ensure that this is working and doesn't regress if we have to edit static files in the future.

**Review by bengolder — CHANGES_REQUESTED** [review]
Needs tests

**Comment by glassresistor** [comment]
Ok I did some soul searching and went and removed a bunch of code that makes the symlink.
Its now just calling compressor and collectstatic together.   If someone changes the Less or JS files such that compiling them fails both the collectstatic command will fail on travis and the unittests will fail when trying to render the template. 
I just verified this locally by putting a typo in require in a js require line and I spent most yesterday watching it fail whenever Less can't find an import.

**Comment by glassresistor** [comment]
Ok I've update the README and did some cleanup.  I think this code is ready to go.

**Review by bengolder — APPROVED** [review]

**Pull request merged**
