### PR TITLE
Add Django Easy Audit

### LINKED ISSUE #779: Write audit log functions (subtask of #658)
**Goal:** To create an automated audit trail and that meets or exceeds the requirements of CJIS
### Details

CJIS specifies the following audit logging requirements for handling of CJI:

https://gist.github.com/bengolder/6cd23f0ebff741c79b6b39b45d3e5a56

This tasks assumes that we would log from the application layer to standard out, pushing our logs into our standard log stream to be directed to appropriate sources.

Create action-specific audit logging functions that can be reused in views and the django admin.
One for each major generic CRUD view.

### PR DESCRIPTION
**Pull request by bengolder**
Closes #779 

### What does this do and why?

This adds audit records for changes to sensitive data.

### Testing & Checks

What does this PR include?
- [x] new dependencies
- [x] migrations
- [ ] data migrations
- [ ] celery tasks
- [ ] changes to environment variables or local settings
- [ ] configuration changes for 3rd party services (Travis, Heroku, AWS, Github, etc) 
- [ ] visual or style changes

Are there any human checks that should be used to verify these changes, such as user acceptance tests (UAT) or manual deployment checks?

No manual human tests are needed.

Any integration or unit tests?

Yes, this adds an integration test to check that tasks performed through the Django Admin site produce the expected records in the audit tables.

This also has a test to ensure that our middleware adequately patches a bug in django-easy-audit.

### Details

This adds [django-easy-audit](https://github.com/soynatan/django-easy-audit/) as a dependency and patches some bugs in the library. We will submit issues & PRs to their codebase later.

This will significantly increase the number of queries for many core transactions. We plan to deploy and monitor the impact, and then judging whether further optimizations are needed.

This library allows us to query the history of changes to some objects and to retrieve their historic state.

### CODE REVIEW

**Comment by glassresistor** [comment]
Taking a look I think the changes and tests are fine.  As per are verbal discussion most of this should go away very soon once our PR is merged or be replaced by our fork if not.  Since this is such a small project with only 80 commits, forking long term is wouldn't be a big deal.

Taking a look a the library itself I have some concerns.  Mainly that logging every model save/update that Django makes is going to at the minimum double our database operations.  At our current traffic that isn't likely to break the bank but it should still slow down requests noticeably for query heavily views.

A better option would be a solution that uses logs instead of the database.  This will both make the logs more secure from tampering and have closer to 0 impact on performance.  I'm happy to research solutions that work better from this perspective or even look into modifying django-easy-audit to optional write to logs instead.

Given that hesitation as a shorterm security measure I think this could work but should be treated as a big Operational change and therefor we should test its metrics on staging for a period of time and then monitor it closely on production.

**Comment by rossettistone** [comment]
To give a little more context on the potential performance degradations:

`easyaudit` is already constrained to only audit a set of models that we care about. As a result, many of our "query count" tests had *no change* when run.
One "query count" test showed an increase from 11 to 19 queries after this library was added, which suggests an 88% increase in query time.

On New Relic, database queries currently comprise about 50ms (30-50%) of our 100-150ms response time. In the worst case, if all of our request times increased by the 88% indicated by that bad test, we'd add something like another 40ms to the response time. There could be additional ORM overhead as well, adding an unknown but likely small additional amount of time.

Overall, we're looking at likely a 50ms increase in page load time. For context, our pages typically load in about 1500ms (1.5 seconds), making this a 3% increase in user experienced load time.

Should the increase be higher than expected, or otherwise problematic, we have some roads for possible performance improvement:
• Disable auditing for objects that are not created by logged-in users (e.g. form submissions)
• Modify the `easyaudit` library to be more efficient with its query strategy. We believe that there's room for improvement in the guts of the library.
• Skip database writes, and use the audits library to create `stdout` logs instead, saved in Papertrail or elsewhere
• perform audit table writes as async tasks

**Comment by glassresistor** [comment]
@rossettistone thanks for the write up, afew things.  our average response time for the past sever days is actually 50ms(lowered in some by whitenoise, don't know how to fixture static files out), the ~1.5s is browser load time which includes everything including download time.  Although browser load time is in the end something we care about its not the metric we should be using as a yardstick because browser load time increases more than linearly if average response time decreases because increasing response time for each response works as both a multiplier and also pushes back dependencies.

On production New Relic queries are taking on average ~50ms.  Looking at requests that are not static files the response time is closer 150ms on average, thats to the server its longer to download and load.  I can't find the average transactions per request.  If we had that it would make this easier it calculate.  Ultimately the easiest way will be just to make sure nothing on staging blows up while we load a bunch of urls together.  [edit] just learned this is only for writes so its probably fine but worth checking[/edit]

Should the increase be higher than expected, or otherwise problematic, we have some roads for possible performance improvement:
• Disable auditing for objects that are not created by logged-in users (e.g. form submissions)
  I think honestly we should be looking to audit everything if possible.
• Modify the easyaudit library to be more efficient with its query strategy. We believe that there's room for improvement in the guts of the library.
  This could be useful in places.
• Skip database writes, and use the audits library to create stdout logs instead, saved in Papertrail or elsewhere
  I think this is key.  I should be easy to make it configurable which logs go to logs and which go to the db.  In our case I think it would be great to log everything reads/writes along with the user(or lack of one) to system logs so that they are immutable and easy to store/work with later.  By making it cheap to log events we can feel free to log everything, and if its immutable we could even in theory monitor our own access effectively.

**Comment by glassresistor** [comment]
As per a verbal conversation with @bengolder and @rossettistone we have discussed that the added latency on Production compared to local should warrant checking that increasing the number of requests doesn't affect request time.

**Comment by bengolder** [comment]
@glassresistor thanks for the input. Overall, for the purpose of shipping this feature, I think your suggestions are good and important to be aware of, but I think we should still deploy the feature and monitor it in production.

Some more detail:
- the current goal of this change is to record sufficient information from our app layer to be able to later produce an adequate CJIS Report. I feel these changes, along with existing logging, adequately  address that need at the app layer. Next in the priority list are a series of infrastructure changes as well as documentation (especially auditability of infrastructure changes and access). However I agree that many of your suggestions would be better for security and performance. In essence, I think they are good but go beyond the goal and are therefore lower priority than other features.
- we do want to use browser load time as good yardstick for _impact on user experience_ which is what we were trying to speak to.

**Pull request merged**
