### PR TITLE
Feature: CSV Export

### LINKED ISSUE #72: Create excel (.xlsx) download for partners
As an org user, I would like to be able to download all data on existing applications to my organization, including the fields that I ask for from applicants.

Criteria:
• Should have proper access controls (org users only, and only for their org)
• Should include the appropriate set of fields for each org user
• Should export in `.xls` format
• Should be accessible via a single button ("Download all data") on the user profile or the application index

Questions to verify:
• is a single button UI sufficient for this?
• should declaration letters be concatenated into a single field?

Tests:
• every field can be exported in `.xls` (assuming it's still in use by an org)

### LINKED ISSUE #964: Export all applications
- [ ]  CSV spreadsheet mockup
- [ ]  Excel 2007 has a row, cell, column limit (so just check those)
- [ ]  Create view that returns a spreadsheet directly
```
import csv

def get_fields_for_org(org):
    # selects context keys from form linked to org 
    # fetches values for those keys from formsubmission
    # get display form
    # iterate over fields & get_display_value
    # exclude declaration letter for now

def get_status_updates_for_app(app):
    # attaches (flat) set of status updates to row 

def csv_for_apps(applications_queryset):
    csv_writer

class AppsCSVView(View):
    # login required

# implement as button "Export all application data as csv" on All Applications Index 

CSVExportSerializer(serializers.Serializer):
# fields

```
UAT
- import into old Excel and ensure it turns out correctly
Testing:
- permission tests
- test that the values are reasonable and nice
Browser test
- navigate to it and click the button and get a file

1.5 days

### PR DESCRIPTION
**Pull request by bengolder**
Closes #72 
Closes #964 

### What does this do and why?

This creates a button that authenticated users can click to download excel files that contain all the applications to their organization. This is useful because many of our partners need to double check data or load it into their own case management databases.

### Testing & Checks

What does this PR include?
- [x] new dependencies
- [ ] migrations
- [ ] data migrations
- [ ] celery tasks
- [ ] changes to environment variables or local settings
- [ ] configuration changes for 3rd party services (Travis, Heroku, AWS, Github, etc) 
- [x] visual or style changes

_Are there any human checks that should be used to verify these changes, such as user acceptance tests (UAT) or manual deployment checks?_

- [ ] We should download some fake apps and open them in Microsoft Excel. 
- [ ] We should also open the link using different versions of Internet Explorer to verify download behavior.
- [ ] We should do a test with a large number of applications for a given org (10,000?)

_Any integration or unit tests?_

This includes tests for the new view that verify that the contents of the resulting csv files look like useful information for our attorney partners.

#### Currently, the link resides on the user's profile page

screen shot 2017-09-13 at 6 34 57 am

### Questions:

- Should we allow Code for America staff to download excel spreadsheets?
    - I would recommend not. The current unhandled behavior lets CfA users download CNL apps
- Is a single link on the profile page a sufficient UI for shipping this feature?
- Which metadata is most important to have for each application?
    - A link back to the original? 
    - Should we include status updates for each application?

### CODE REVIEW

**Comment by glassresistor** [comment]
So the code in general looks good.  I want to note that creating Excel spreadsheets using user created content has a higher potential for malware injection than PDFs do.  Specifically Excel files ae allowed to run arbitrary code unlike PDFs.

This should be given even more scrutiny than PDF injection.  Another option would be to switch to using CSV which doesn't have this problem.

**Comment by jazmynlatimer** [comment]
The location of the Export all applications button is not in the right location. In the mockups, the button is located on the All Apps index page. Currently it is located on the page you see when you first log in. My reasoning behind having the button on the All Apps Index tab is 1) the button should be nearest to the items its taking an action on - so in this case, all of the current applications and 2) this login page is very hard to find if you are already logged in (you have to know to click on your name in the nav bar, even though your name doesn't have any affordances of a link), and I have not yet witnessed a user who actually uses this page - the only time they see it is the first time they log in.  What was the thinking behind switching the location from the mockups?

**Comment by jazmynlatimer** [comment]
Where the export button should be located:
screen_shot_2017-06-28_at_3 27 45_pm


Current location of Export button:
screen shot 2017-09-19 at 11 21 50 am

**Comment by sarahlizwhite** [comment]
No issues found. Agreed with Jazmyn's suggestion - more usable and find-able if button is on application dashboard screen. 

Will there be a functionality to also export SN data? If not, why not? If later, when? This is something to include in partner message as people will ask.

**Comment by bengolder** [comment]
Sounds great! We simply weren't aware that mockups existed for this and built a minimal UI with the hope of further review (posed the question about UI explicitly in the PR notes above). We will move the link to the app index page as shown in the mocks.

Regarding the inclusion of status updates, we can, it wasn't clear in the ticket, so we asked about it above in the Questions section. @TiffanyAndrews would you like us to include status updates in the download?

@sarahlizwhite & @jazmynlatimer can you confirm if you were able to easily open the export in Microsoft Excel?

**Comment by sarahlizwhite** [comment]
confirming excel worked fine!

**Comment by bengolder** [comment]
@jazmynlatimer @sarahlizwhite I have moved the link to the "All" Applications page. Note that I excluded it from "Needs Update" and "Unread" tabs, since the link is only currently capable of exporting all apps. Might be good to consider allowing it to be scope the export in the future.

**Review by lkogler — APPROVED** [review]
Looks good to me

**Comment by sarahlizwhite** [comment]
Checking on to see if a partner feature announcement was also created to pair with this deployment? @bengolder I think this was in @TiffanyAndrews ' camp but don't want it to fall through the cracks. 

See example from ER: https://docs.google.com/document/d/1HwCNgUERs5m9_dsYcL-t5LLo9Qp0ySXbufCljbOAFRs/edit

**Comment by bengolder** [comment]
@sarahlizwhite no announcement has been created that I am aware of. I would trust your judgement on whether it's needed, and we are happy to supply screenshots or some more explanation if that would help put it together.

**Pull request merged**
