### PR TITLE
add robots.txt

### PR DESCRIPTION
**Pull request by glassresistor**
#754

### CODE REVIEW

**Comment by bengolder** [comment]
I need to add a list of public indexable pages

**Comment by bengolder** [comment]
public URLs:

```
/
/apply/
/privacy/
/partners/
/partners/*/
/recommendation-letters/
/personal-statement/
/stats/
```

**Comment by glassresistor** [comment]
I've gone ahead and updated the robots file to use the new urls.  Going to move to a file of its own though

**Comment by glassresistor** [comment]
this covers #784 #754

**Comment by jennifermarie** [comment]
@glassresistor I merged the hotfix that includes the new `phone` app here

**Pull request merged**
